name: 'CD for my pipeline :)'
'on':
  push:
    branches:
      - main
  workflow_dispatch: null
jobs:
  deploy_code:
    name: Deploy my Great Databricks Pipeline to production
    uses: ./reusable_databricks_code_deployment.yml@v1.0.0
    with:
      databricks_code_path: data-chisel/test_scripts/
      service_code_file: pytest_scripts.py
    secrets:
      DATABRICKS_HOST_URL: '${{ secrets.MY_DATABRICKS_HOST }}'
      DATABRICKS_TOKEN: '${{ secrets.MY_DATABRICKS_TOKEN }}'
